### ISSUE TITLE
Set up Storybook

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/bulletproof-react-clone#18]
## Deliverables

Storybook and Chromatic are available for this project.

## Todos

- [x] Set up Storybook
  - [x] Integrate Tailwind CSS
  - [x] Default background setting
- [ ] Set up Chromatic
  - [ ] Automatic deployment via GitHub action
- [x] Create stories
  - [x] Button
  - [x] Spinner

## References

- Storybook: https://storybook.js.org/
- Tailwind Integration: https://storybook.js.org/recipes/tailwindcss

## Other notes

Deployed to Chromatic, but Tailwind CSS was not working. 
Deploy to Chromatic will be done later.
