### ISSUE TITLE
Clone the original repository and launch the application to see the output

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/bulletproof-react-clone#2]
## Deliverables

To understand what is the outcome of bulletproof-react app.

## Todos

- [x] Clone the repo
- [ ] ~~Run the app~~
=> There is a compile error. See the "Other notes" section.
- [x] Check the demo site

### Repo

https://github.com/alan2207/bulletproof-react

### Demo

https://bulletproof-react-app.netlify.app/

### Compile error in "Form.tsx"

https://github.com/alan2207/bulletproof-react/issues/112
