### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/bulletproof-react-clone#25]
## Deliverables

A user can log in to the application when a valid credential is given.
A user can't log in to the application when an invalid credential is given.

## Todos

- [x] Install libraries
  - [x] MSW
  - [x] @tanstack/react-query
  - [x] react-query-auth
  - [x] axios
  - [x] mswjs/data
  - [x] nanoid
  - [ ] vitest
  - [ ] Chance
  - [ ] testing-libarary-react
- [x] Mock API
  - [x] Define mocks
  - [x] Integrate mocks with Service Worker
- [x] Authentication
  - [x] Register
  - [x] Login
  - [x] onSuccess
  - [x] Check authentication on page load
  - [x] Sign out
  - [x] Loader component
- [ ] Test

## References

- MSW: https://mswjs.io/
- react-query-auth: https://github.com/alan2207/react-query-auth
- react-query: https://tanstack.com/query/latest
- axios: https://github.com/axios/axios
- mswjs/data: https://github.com/mswjs/data
- nanoid: https://github.com/ai/nanoid
- jsonwebtoken: https://github.com/auth0/node-jsonwebtoken
- jsonwebtoken-esm: https://github.com/sanity-io/jsonwebtoken-esm
- jase: https://github.com/panva/jose
- vitest: https://vitest.dev/
- Chance: https://chancejs.com/
- testing library react: https://testing-library.com/docs/react-testing-library/intro/
- happy-dom: https://github.com/capricorn86/happy-dom

### Issue with JWT package

`jsonwebtoken` doesn't work with ES6 modules. So I changed it to `jsonwebtoken-esm`.
https://github.com/auth0/node-jsonwebtoken/issues/655

### Test
`RegiterForm` and `LoginForm` test will be done later.
