### ISSUE TITLE
Set up static checking & git hooks

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/bulletproof-react-clone#5]
## Deliverables

Set up static checks. See the details below in Todos.

## Todos

- [x] Set up tsconfig
=> No change needed.
- [x] Set up Eslint
- [x] Set up Prettier
- [x] Git hooks
  - [x] husky
  - [x] lint-staged
  - [x] npm-run-all

## References

- tsconfig: https://www.typescriptlang.org/ja/tsconfig
- ESLint: https://eslint.org/
- Prettier: https://prettier.io/
- husky: https://typicode.github.io/husky/#/
- lint-staged: https://github.com/okonet/lint-staged
- npm-run-all: https://www.npmjs.com/package/npm-run-all

## Other notes

None
